services:
  backend-a:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-a
    networks:
      lbnet:
        ipv4_address: 10.10.0.2
    cap_add: [ NET_ADMIN ]
    sysctls:
      # ARP 靜默
      net.ipv4.conf.all.arp_ignore:   1
      net.ipv4.conf.all.arp_announce: 2
      net.ipv4.conf.all.accept_local: 1   
      net.ipv4.conf.all.rp_filter:    0    

  backend-b:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-b
    networks:
      lbnet:
        ipv4_address: 10.10.0.3
    cap_add: [ NET_ADMIN ]
    sysctls:
      net.ipv4.conf.all.arp_ignore:   1
      net.ipv4.conf.all.arp_announce: 2
      net.ipv4.conf.all.accept_local: 1
      net.ipv4.conf.all.rp_filter:    0

  lb:
    build:
      context: .
      dockerfile: Dockerfile
      # 如需切换不同 XDP 目标，传 ARG：
      args:
        - TARGET=xdp_dsr
    container_name: lb
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend-a
      - backend-b
    # ENTRYPOINT 仍由 Dockerfile 决定，那里会自动找 bridge

  client:
    image: curlimages/curl
    container_name: client
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.4

  client-test1:
    image: curlimages/curl
    container_name: client-test1
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.11

  client-test2:
    image: curlimages/curl
    container_name: client-test2
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.12

  client-test3:
    image: curlimages/curl
    container_name: client-test3
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.13

networks:
  lbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

