services:
  backend-a:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-a
    networks:
      lbnet:
        ipv4_address: 10.10.0.2
    cap_add: [ NET_ADMIN ]

  backend-b:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-b
    networks:
      lbnet:
        ipv4_address: 10.10.0.3
    cap_add: [ NET_ADMIN ]

  lb:
    image: nginx:1.25-alpine
    container_name: lb
    networks:
      lbnet:
        ipv4_address: 10.10.0.5
    depends_on:
      - backend-a
      - backend-b
    volumes:
      - ./nginx/l7.conf:/etc/nginx/conf.d/default.conf:ro

  client:
    image: curlimages/curl
    container_name: client
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.4

networks:
  lbnet:
    driver: default
    ipam:
      config:
        - subnet: 10.10.0.0/24

