services:
  backend-a:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-a
    networks:
      lbnet:
        ipv4_address: 10.10.0.2
    cap_add: [ NET_ADMIN ]

  backend-b:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend-b
    networks:
      lbnet:
        ipv4_address: 10.10.0.3
    cap_add: [ NET_ADMIN ]

  lb:
    build:
      context: .
      dockerfile: Dockerfile
      # 如需切换不同 XDP 目标，传 ARG：
      args:
        - TARGET=xdp_lb
    container_name: lb
    privileged: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.5
    cap_add: [ NET_ADMIN ]
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend-a
      - backend-b
    # ENTRYPOINT 仍由 Dockerfile 决定，那里会自动找 bridge

  client:
    image: curlimages/curl
    container_name: client
    entrypoint: sh
    stdin_open: true
    tty: true
    networks:
      lbnet:
        ipv4_address: 10.10.0.4

networks:
  lbnet:
    driver: default
    ipam:
      config:
        - subnet: 10.10.0.0/24

